name: CI
on: [ push, workflow_dispatch ]

jobs:
  run containers on VM:
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: ssh connection and start docker containers
        run: ssh valera@34.88.77.186 "/home/paramone_val/cm selenoid start &
          docker start my_postgres &
          exit"
  tests:
    runs-on: ubuntu-latest
    needs: run containers on VM
    continue-on-error: true
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: Get repository
        uses: actions/checkout@v
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v
      - name: Execute gradle task
        run: ./gradlew clean gui -Dbrowser=${{ matrix.browser }}

  Stop containers:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: ssh connection and stop docker containers
        run: ssh valera@34.88.77.186 "/home/paramone_val/cm selenoid stop &
          docker stop my_postgres &
          exit"