name: CI
on: [ push, workflow_dispatch ]

jobs:
  run_containers_on_VM:
    runs-on: ubuntu-latest
    steps:
#      - uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.PRIVATE_KEY }}
#          known_hosts: ${{ secrets.SSH_HOST }}
#      - name: ssh connection and start docker containers
#        run: ssh valera@{{ secrets.HOST_IP } "./cm selenoid start &
#          docker start pdp-postgres &
#          exit"
  tests:
    runs-on: ubuntu-latest
#    needs: run_containers_on_VM
#    continue-on-error: true
#    strategy:
#      matrix:
#        browser: [ chrome, firefox ]
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Execute gradle task
        run: |
          echo "{{ secrets.PRIVATE_KEY }}" >> key
          scp -i key LOCAL_FILE_PATH valera@{{ secrets.HOST_IP }}:~/results
#      - name: Setup java
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 11
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#      - name: Execute gradle task
#        run: ./gradlew clean gui -Dbrowser=${{ matrix.browser }}
#
#  stop_containers_on_VM:
#    runs-on: ubuntu-latest
#    needs: tests
#    steps:
#      - uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.PRIVATE_KEY }}
#          known_hosts: ${{ secrets.SSH_HOST }}
#      - name: ssh connection and stop docker containers
#        run: ssh valera@{{ HOST_IP }} "./cm selenoid stop &
#          docker stop pdp-postgres &
#          exit"