name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_host: ${{ secrets.SSH_HOST }}
          run: ssh valera@34.88.77.186 "docker my_postgres start & docker ps"

#      - run: |
#          ssh -tt -i src/test/resources/key valera@34.88.77.186
#          docker my_postgres start
#          docker ps
#          exit
