name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: echo '${{ secrets.PUBLIC_KEY }}' > key
             ssh -i key googleCloud@34.88.77.186
             docker my_postgres start
             exit
             ./gradlew clean gui