name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - run: |
    
          echo '${{ secrets.PRIVATE_KEY }}' > key
          ssh -i src/test/resources/key valera@34.88.77.186
          docker my_postgres start
          docker ps
          exit