name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Pull
        run: ssh valera@34.88.77.186 "docker start my_postgres && ls"

#      - run: |
#          ssh -tt -i src/test/resources/key valera@34.88.77.186
#          docker my_postgres start
#          docker ps
#          exit
