name: CI
on: [ push ]

jobs:
  tests:
    strategy:
      matrix:
        browser: [chrome, firefox]
    runs-on: ubuntu-latest
    steps:
      - name: Start containers
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: ssh connection and start docker containers
        run: ssh valera@34.88.77.186 "/home/paramone_val/cm selenoid start &
          docker start my_postgres &
          exit"

      - name: Get repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle task
        run: ./gradlew clean gui -Dbrowser=${{ matrix.browser }}

      - name: Stop containers
        run: ssh valera@34.88.77.186 "/home/paramone_val/cm selenoid stop &
              docker stop my_postgres &
              exit"

